version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8000:8000"  # Map container's port 8000 to host's port 8000
    network_mode: "bridge"  # Use bridge networking
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
